apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-app
  labels:
    app: bookmyshow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
      - name: BookMyShow
        image: pradeep905/bookmyshow:latest  # Replace with your Docker image
        ports:
        - containerPort: 1000  # Replace with the port your app runs on
